/*
VLESS Config Switcher - A lightweight configuration switcher for VLESS profiles.
Copyright (C) 2026  LimonTH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://gnu.org>.
*/

package tun

import (
	"fmt"
	"net"

	"github.com/vishvananda/netlink"
)

// Параметры маршрутизации через TUN.
type RouteConfig struct {
	InterfaceName string
	DNSServers    []string
	BypassRoutes  []string
}

// DefaultRouteConfig возвращает конфиг маршрутизации по умолчанию.
func DefaultRouteConfig(ifaceName string) *RouteConfig {
	return &RouteConfig{
		InterfaceName: ifaceName,
		DNSServers:    []string{"1.1.1.1", "8.8.8.8"},
		BypassRoutes:  []string{},
	}
}

// SetupRoutes настраивает маршрут по умолчанию через TUN.
func SetupRoutes(cfg *RouteConfig) error {
	if _, err := netlink.LinkByName(cfg.InterfaceName); err != nil {
		return fmt.Errorf("cannot find interface %s: %w", cfg.InterfaceName, err)
	}

	defaultRoutes, err := netlink.RouteListFiltered(netlink.FAMILY_V4, &netlink.Route{
		Dst: nil,
	}, netlink.RT_FILTER_DST)
	if err == nil {
		for _, route := range defaultRoutes {
			_ = netlink.RouteDel(&route)
		}
	}

	for _, bypassCIDR := range cfg.BypassRoutes {
		_, dst, err := net.ParseCIDR(bypassCIDR)
		if err != nil {
			return fmt.Errorf("invalid bypass route %s: %w", bypassCIDR, err)
		}
		bypassRoute := &netlink.Route{
			Dst: dst,
		}
		if err := netlink.RouteAdd(bypassRoute); err != nil {
			return fmt.Errorf("failed to add bypass route %s: %w", bypassCIDR, err)
		}
	}

	if err := runCommand("ip", "route", "replace", "default", "dev", cfg.InterfaceName); err != nil {
		return fmt.Errorf("failed to add default route through %s: %w", cfg.InterfaceName, err)
	}

	return nil
}

// CleanupRoutes удаляет все маршруты для TUN-интерфейса.
func CleanupRoutes(ifaceName string) error {
	link, err := netlink.LinkByName(ifaceName)
	if err == nil {
		routes, err := netlink.RouteList(link, netlink.FAMILY_V4)
		if err == nil {
			for _, route := range routes {
				_ = netlink.RouteDel(&route)
			}
		}
		return nil
	}

	links, err := netlink.LinkList()
	if err == nil {
		for _, l := range links {
			if l.Attrs().Name == ifaceName {
				routes, err := netlink.RouteList(l, netlink.FAMILY_V4)
				if err == nil {
					for _, route := range routes {
						_ = netlink.RouteDel(&route)
					}
				}
				return nil
			}
		}
	}

	_ = runCommand("ip", "route", "flush", "dev", ifaceName)
	return nil
}

// SetDNS устанавливает DNS-серверы.
func SetDNS(servers []string) error {
	for _, server := range servers {
		err := runCommand("resolvectl", "dns", "tun0", server)
		if err != nil {
			return setResolvConf(servers)
		}
	}
	return nil
}

// RestoreDNS восстанавливает DNS.
func RestoreDNS() error {
	err := runCommand("resolvectl", "dns", "tun0", "")
	if err != nil {
		return setResolvConf([]string{})
	}
	return nil
}

// setResolvConf записывает /etc/resolv.conf.
func setResolvConf(servers []string) error {
	content := "# Generated by vpn-switcher\n"
	for _, s := range servers {
		content += fmt.Sprintf("nameserver %s\n", s)
	}

	return runCommand("sh", "-c", fmt.Sprintf("echo '%s' > /etc/resolv.conf", content))
}

// RemoveBypassRoute удаляет bypass-маршрут для VLESS-сервера.
func RemoveBypassRoute(vlessServer string) error {
	if vlessServer == "" {
		return nil
	}
	return runCommand("ip", "route", "del", vlessServer+"/32")
}
